import { PokemonList } from '@/components/pokemonList'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { PokemonInterface } from 'types/pokemonType'

export default function Home() {
  const initialArray: any[] = []
  const [data, setData] = useState<any[]>(initialArray)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
      setLoading(true)
      fetch('https://pokeapi.co/api/v2/pokemon?offset=10&limit=10')
        .then((res) => res.json())
        .then((res) => {
          let i: PokemonInterface[] = []
          res.results.map( (_: any) => {
            fetch(_.url).then((res) => res.json()).then((res) => {
              let getPokemonData: PokemonInterface = { name: _.name, url: _.url, svg: res.sprites.other.dream_world.front_default }
              setData(initialArray => [...initialArray, getPokemonData]);
            })
          })
          
        })
    }, [])
  
  console.log(data)
  
    
  return (
    <>
      <Head>
        <title>Pokemon API | Eka Bachrudin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='flex flex-row items-center space-x-5 justify-center'>
              <Image alt="logo" src={"/images/pokeball.png"} width={70} height={70} />
              <div>
                <p>POKEMON API</p> <span className='text-xs'>By EKa Bachrudin</span>
              </div>
        </div>
      <PokemonList  result={data} />
    </>
  )
}
